export const LEAGUES = [
  {
    id: "PL",
    name: "Premier League 2024/2025",
    country: "England",
    color: "#3d195b",
    logo: "https://media.api-sports.io/football/leagues/39.png",
  },
  {
    id: "PD",
    name: "La Liga 2024/2025",
    country: "Spain",
    color: "#c60b1e",
    logo: "https://media.api-sports.io/football/leagues/140.png",
  },
  {
    id: "BL1",
    name: "Bundesliga 2024/2025",
    country: "Germany",
    color: "#d00000",
    logo: "https://media.api-sports.io/football/leagues/78.png",
  },
  {
    id: "SA",
    name: "Serie A 2024/2025",
    country: "Italy",
    color: "#003399",
    logo: "https://media.api-sports.io/football/leagues/135.png",
  },
  {
    id: "FL1",
    name: "Ligue 1 2024/2025",
    country: "France",
    color: "#1a3a6b",
    logo: "https://media.api-sports.io/football/leagues/61.png",
  },
];

export const CHAMPIONS = {
  PL: [
    {
      title: "แชมป์ลีก",
      label: "Premier League",
      club: "ลิเวอร์พูล",
      detail: "สมัยที่ 20",
      logo: "https://media.api-sports.io/football/teams/40.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Premier League",
    },
    {
      title: "เอฟเอ คัพ",
      label: "FA Cup",
      club: "คริสตัล พาเลซ",
      detail: "แชมป์ประวัติศาสตร์ 119 ปีของสโมสร",
      logo: "https://media.api-sports.io/football/teams/52.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "FA Cup",
    },
    {
      title: "คาราบาว คัพ",
      label: "League Cup",
      club: "นิวคาสเซิล ยูไนเต็ด",
      detail: "แชมป์คาราบาว คัพ",
      logo: "https://media.api-sports.io/football/teams/34.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "League Cup",
    },
  ],
  PD: [
    {
      title: "แชมป์ลีก",
      label: "La Liga",
      club: "บาร์เซโลนา",
      detail: "ภายใต้การคุมทีมของ ฮันซี ฟลิก",
      logo: "https://media.api-sports.io/football/teams/529.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "La Liga",
    },
    {
      title: "โกปา เดล เรย์",
      label: "Copa del Rey",
      club: "บาร์เซโลนา",
      detail: "คว้าแชมป์โกปา เดล เรย์",
      logo: "https://media.api-sports.io/football/teams/529.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Copa del Rey",
    },
    {
      title: "สแปนิช ซูเปอร์คัพ",
      label: "Supercopa",
      club: "บาร์เซโลนา",
      detail: "ทำ Triple Champ ในประเทศได้สำเร็จ",
      logo: "https://media.api-sports.io/football/teams/529.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Spanish Super Cup",
    },
  ],
  SA: [
    {
      title: "แชมป์ลีก",
      label: "Serie A",
      club: "นาโปลี",
      detail: "คว้าแชมป์สมัยที่ 4 หลังชนะกายารี่ 2-0",
      logo: "https://media.api-sports.io/football/teams/492.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Serie A",
    },
    {
      title: "โคปปา อิตาเลีย",
      label: "Coppa Italia",
      club: "โบโลญญ่า",
      detail: "แชมป์โคปปา อิตาเลีย",
      logo: "https://media.api-sports.io/football/teams/500.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Coppa Italia",
    },
  ],
  BL1: [
    {
      title: "แชมป์ลีก",
      label: "Bundesliga",
      club: "บาเยิร์น มิวนิก",
      detail: "กลับมาทวงแชมป์คืนจากเลเวอร์คูเซินได้สำเร็จ",
      logo: "https://media.api-sports.io/football/teams/157.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Bundesliga",
    },
    {
      title: "เดเอฟเบ โพคาล",
      label: "DFB-Pokal",
      club: "บาเยิร์น มิวนิก",
      detail: "คว้าแชมป์ DFB-Pokal",
      logo: "https://media.api-sports.io/football/teams/157.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "DFB-Pokal",
    },
  ],
  FL1: [
    {
      title: "แชมป์ลีก",
      label: "Ligue 1",
      club: "ปารีส แซงต์-แชร์กแมง",
      detail: "คว้าแชมป์สมัยที่ 13 ทิ้งห่างอันดับสองถึง 19 แต้ม",
      logo: "https://media.api-sports.io/football/teams/85.png",
      trophy: "https://img.icons8.com/color/48/000000/trophy.png",
      trophyLabel: "Ligue 1",
    },
  ],
};
